### PR TITLE
Make ToProperty work properly on Indexers

### PR DESCRIPTION
**Pull request by timotei**
In order for Data Bindings to work properly, we need to signal the right property name, in the case of indexers.

### CODE REVIEW

**Comment by kentcb** [comment]
This is targeting rxui6 rather than rxui7. Is this intentional?

**Comment by timotei** [comment]
Yeah, I wanted to fix rxui6 first and then it can be forwardported (cherry picked) on rxui7 as well. I can do the rxui7 branch fix also.

**Comment by timotei** [comment]
@paulcbetts  You mentioned in the RxUI 7 TODO list:

> Figure out how to make ToProperty fast but also not troll people

I think this PR will help towards the "not troll people" direction, together with the PR for rxui7: https://github.com/reactiveui/ReactiveUI/pull/1084

**Comment by timotei** [comment]
@kentcb Can we have this merged in rxui6 as well? Thanks!

**Comment by flagbug** [comment]
@timotei RxUI6 is EOL, i.e there won't be any more releases. If you retarget this onto RxUI7, we can merge it

**Comment by flagbug** [comment]
@timotei Nevermind, I just saw that you've created a separate PR for RxUI7 that already got merged

**Comment by timotei** [comment]
OK then. I'll close this.

**Pull request closed without merging**
