### PR TITLE
Feature Add Reactive, ObservableAsProperty and ReactiveCommand Source Generators

### PR DESCRIPTION
**Pull request by ChrisPulman**
**What kind of change does this PR introduce?**

Feature

**What is the current behavior?**

Fody is currently available for `[Reactive]` and `[ObservableAsProperty]`

**What is the new behavior?**

`[Reactive]` `[ObservableAsProperty]` Field Attributes and a `[ReactiveCommand]` Method Attribute with Source Generators now added.

**What might this PR break?**

There are differences between the old Fody injector and the new Source Generator both in the Attribute location and the operation.

Documentation must be updated to coincide with a release.

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by glennawatson** [comment]
There is a separate repo for the source generators, probably best to separate since source-generators don't have a dependency on the rxui version.

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI.ObjectGenerators

**Comment by ChrisPulman** [comment]
> https://github.com/reactiveui/ReactiveUI.ObjectGenerators
> 
> >  GitHub**[GitHub - reactiveui/ReactiveUI.ObjectGenerators: Use source generators to generate objects.](https://github.com/reactiveui/ReactiveUI.ObjectGenerators)**Use source generators to generate objects. . Contribute to reactiveui/ReactiveUI.ObjectGenerators development by creating an account on GitHub.

Thank you, I will move it to this repository.
It has no direct dependency to ReactiveUI.

**Comment by ChrisPulman** [comment]
Moved to https://github.com/reactiveui/ReactiveUI.SourceGenerators/pull/3

**Pull request closed without merging**
