### PR TITLE
Remove ViewContractAttribute

### LINKED ISSUE #880: Nuke ViewContractAttribute
This attribute is of questionable utility. Unless there are objections, kill it with :fire:

### PR DESCRIPTION
**Pull request by kentcb**
This PR fixes #880 by removing the `ViewContractAttribute` and related lookup logic in `ViewLocator`.

### CODE REVIEW

**Comment by gluck** [comment]
Doubt the chmod change on both files is on purpose :)

**Comment by kentcb** [comment]
@gluck: there's a chmod change?

**Comment by gluck** [comment]
Didn't pull it locally, but that's what github web UI says, 644->755

**Comment by kentcb** [comment]
Ah, now I see it. I have no explanation :confused:

**Pull request merged**
