### PR TITLE
feature: add the tizen30 platform to reactiveui

### PR DESCRIPTION
**Pull request by ghuntley**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature

**The Plan**
- [ ] Get a clean msbuild without referencing any Tizen platform specifics. (**we are here; current attempts blocked at this stage**)
- [ ] Generate and package `reactiveui-events` for `tizen30` via downloading packages from NuGet.
- [ ] Start adding platform specific/public API surface to `reactiveui`

**Other information**:

* The TFM is `tizen30` as per https://github.com/NuGet/Home/issues/4175 which was implemented in over at https://github.com/NuGet/NuGet.Client/pull/1083/files
* NuGet v4.1 (now released) has support for this TFM.
* We are super-early adopters - expect 🐉's - based on some googling only other person who has tried this yet is @maltegoetz  https://github.com/jamesmontemagno/SettingsPlugin/pull/72/files

Blocked until figure out how to multi-target the platform correctly:

Error message after https://github.com/reactiveui/ReactiveUI/pull/1387/commits/7e9535a191b91ed94dfd42ffe4f235e5a78a1ba1

image

Error message after https://github.com/reactiveui/ReactiveUI/pull/1387/commits/2fb2ba45d2d25a0df55cee215069980f7f81030f

image

AppVeyor does not have the tizen SDK's installed but I do on my local machine (obtained yesterday from https://developer.tizen.org/development/tizen-.net-preview/getting-started/installing-visual-studio-tools-tizen). All screenshots/logs are from my local machine.

/cc @WonyoungChoi

### CODE REVIEW

**Comment by onovotny** [comment]
I added preliminary support for Tizen in the extras package. You'll need the CI feed for now:
`https://www.myget.org/F/msbuildsdkextras/api/v3/index.json`

It's `1.0.5-beta.51`. Based on the way the Xamarin TFM's and all are structured, you'll likely need to do conditional `PackageReference` for the `tizen30` TFM for the tizen specific packages you want/need since no one seems to be using the `tizen30` tfm in their packages yet.

**Comment by onovotny** [comment]
@ghuntley Tizen now will build correctly. What you need is to update the shared\Registrations.cs since there's nothing in there for Tizen.

There is a `TIZEN` and `TIZEN3_0` symbol defined if you want to condition off of either of those.

**Comment by ghuntley** [comment]
Thanks for helping out here @onovotny.

**Comment by WonyoungChoi** [comment]
I am sorry to inform you late. Tizen .NET preview 4 has been released last week. Unfortunately, however, the Tizen TFM has not been used yet. I recommend making a seperated package for tizen and using netstandard for it until the Tizen TFM is ready. And please use Tizen.NET 3.0.0 instead of Tizen.Library. The Tizen.Library will not be managed anymore.

**Comment by onovotny** [comment]
Thanks @WonyoungChoi, good to know. If it helps, I've added support for the Tizen TFM's in my MSBuild.Sdk.Extras package so that SDK-style projects can build them.

**Comment by onovotny** [comment]
@WonyoungChoi The directions are here, https://github.com/onovotny/MSBuildSdkExtras/blob/master/README.md#using-the-package, and I'm happy to help any way I can.

**Comment by WonyoungChoi** [comment]
@onovotny Thank you for adding Tizen tfm to your package. :) It will help us a lot.

**Comment by onovotny** [comment]
@WonyoungChoi it probably won't help with the application projects, since that requires support from your project system for debugging, but it "teaches" the SDK-style project system how to build class libraries that can target your platform. Please feel free to reach out to me anytime if you need help. My email is oren at novotny dot org.

**Comment by ghuntley** [comment]
Linking https://github.com/dotnet/corert/issues/4856 in with this thread.

**Comment by ghuntley** [comment]
Replaced by #1546

**Pull request closed without merging**
