### PR TITLE
housekeeping: add more folks into their team

### PR DESCRIPTION
**Pull request by ghuntley**
**What is the current behavior? (You can also link to an open issue here)**

"core" team? pfft. 

**What is the new behavior (if this is a feature change)?**

recognise all the peeps

### CODE REVIEW

**Comment by glennawatson** [comment]
Lets get this baby in there :)

**Comment by worldbeater** [comment]
When I try to view a team I constantly get 404 exceptions. 
If I log out, click on one of these links redirects me to Github login page.
People in Slack say, this is a permissions issue. 
Can we do something with this?

**Comment by ghuntley** [comment]
It's a GitHub limitation. You have to be in a team to be able to view who's in them or request to join.

**Comment by ghuntley** [comment]
If you would like to join a team ask in #reactiveui-succession in slack.

**Pull request merged**
