### PR TITLE
updated all projects that ref xam forms to 1.3.1-6294-pre1

### PR DESCRIPTION
**Pull request by detroitpro**
I am not sure if you want to update to use a pre-release version of Xamarin Forms but this closes issue #786

note: since I don't have Xamarin.Mac I added a XamForms specific sln in this PR.

### CODE REVIEW

**Comment by paulcbetts** [comment]
I can't use prereleases because that'll make ReactiveUI itself prerelease :(

**Comment by detroitpro** [comment]
That's fine - just delete this PR

However; Xamarin forms now has a main Application class that is used instead of the platform specific SetPage and window.rootViewController; that will effect the design of the RoutedViewHost (I think...it will need to derive from Xamarin.Forms.Application)

image

**Comment by paulcbetts** [comment]
@ermau Yo whatchu shipping breaking changes in point releases imma break up wit u

**Comment by shiftkey** [comment]
screen shot 2015-01-03 at 9 22 01 pm

**Comment by Alxandr** [comment]
1.3 has been released. Would you mind updating the references and publishing to NuGet? I just started playing with this, and when I finally thought I figured out how (some of) the screws fit together, `BindableProperty.Create` blew up in my face :(

https://www.nuget.org/packages/Xamarin.Forms/1.3.0.6292

**Comment by ermau** [comment]
> @ermau Yo whatchu shipping breaking changes in point releases imma break up wit u

What breaking changes? 1.3.0 -> 1.3.1 is purely adding Unified support which changes no API from our perspective. Any rebuilding required is beyond XF's control.

**Comment by paulcbetts** [comment]
@ermau Yeah, but 1.2.x -> 1.3.x changes erry'thing

**Comment by ermau** [comment]
@paulcbetts I can't think of any APIs we _changed_, there should only be additions (and some [Obselete], but all those still work).

**Comment by paulcbetts** [comment]
@Alxandr 1.3.0 doesn't help us any, at least wrt Unified support - it seems like 1.3.1 is coming soon so I'm going to hold off until then

**Comment by Alxandr** [comment]
Oh dang :-/.

Could you do a pre-release of RXUI in the mean time?

**Comment by paulcbetts** [comment]
@Alxandr Sorry, I don't do prereleases. You can definitely just build your own ReactiveUI.XamForms though (or just include the code in your app)

**Comment by Alxandr** [comment]
Hold on a second. The latest stable release of Xamarin.Forms causes `MethodNotFoundException` inside `ReactiveUI.XamForms`. This would indicate that reactiveui uses one or more methods of xamarin.forms that doesn't exist anymore. How can updating to the latest stable version not fix this?

**Comment by felipeleusin** [comment]
Just wanted to chime in.... doing some tests here and simply switching the AppBootstrapper CreateMainView to something like CreateFormsApplication that returns an application that has a MainPage = new RoutedHostView() works like a charm.

I think there is probably some code that can be done to with the SuspendHelper now that FormsApplication has a OnSleep/OnResume/OnStart but haven't looked into it yet

**Comment by ghuntley** [comment]
@paulcbetts are you okay with doing pre-release nuget packages once the CICD is set up?

**Comment by flagbug** [comment]
Closing this, as we're now on a newer version

**Pull request closed without merging**
