### PR TITLE
feature: target monoandroid80 instead of monoandroid70 and upgraded to 26.1.0.1 support lib

### LINKED ISSUE #1517: VS2017 15.4 issues
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
VS2017 update 4 with latest Xamarin for VS update stops events building correctly
- EventBuilder builds against reference assemblies installed by Xamarin (e.g. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid) which is now 8
- ReactiveUI.Events builds against MonoAndroid70, which doesn't have the DrmInfoEventArgs types

Particular events are around DRM
```
public IObservable<Android.Media.MediaPlayer.DrmInfoEventArgs> DrmInfoEvent {
	get { return Observable.FromEventPattern<System.EventHandler<Android.Media.MediaPlayer.DrmInfoEventArgs>, Android.Media.MediaPlayer.DrmInfoEventArgs>(x => This.DrmInfoEvent += x, x => This.DrmInfoEvent -= x).Select(x => x.EventArgs); }
}

public IObservable<Android.Media.MediaPlayer.DrmPreparedEventArgs> DrmPrepared {
	get { return Observable.FromEventPattern<System.EventHandler<Android.Media.MediaPlayer.DrmPreparedEventArgs>, Android.Media.MediaPlayer.DrmPreparedEventArgs>(x => This.DrmPrepared += x, x => This.DrmPrepared -= x).Select(x => x.EventArgs); }
}
```

image

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Upgrade VS2017 and Xamarin to latest.

**What is the expected behavior?**
Can build RxUI, events etc.

**What is the motivation / use case for changing the behavior?**
Being able to build

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

Latest master, Android platform and VS2017.4+Xamarin ~4.7

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

### PR DESCRIPTION
**Pull request by ghuntley**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

feature

**What is the current behavior? (You can also link to an open issue here)**

Builds will be broken when #1517 transitions to stable.

**What is the new behavior (if this is a feature change)?**

Upgraded to monoandroid80 and v25.4.0.2 support lib

**What might this PR break?**

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

Fixes #1517

### CODE REVIEW

**Comment by ghuntley** [comment]
Blocked until AppVeyor updates their `Preview` image. Let's go for #1520

**Comment by ghuntley** [comment]
Will need to +bump https://github.com/reactiveui/ReactiveUI/pull/1520/files#diff-6cfa8e971d51053620e8a9916d81e5d7R33 before merging this PR

**Comment by ghuntley** [comment]
Reminder that `reactiveui.events` pinning for android may need to be updated... https://github.com/reactiveui/ReactiveUI/pull/1520/files#diff-6cfa8e971d51053620e8a9916d81e5d7R33D

**Comment by Qonstrukt** [comment]
The build.cake now reads the ANDROID_HOME environment variable and supplies it to MSBuild. If you leave it empty, or if it's unspecified, the Android build task automatically falls back to the default path.

**Comment by Qonstrukt** [comment]
The upgrade to Support Libraries 26.1.0.1 introduced a breaking change by removing `ReactiveActionBarActivity`, but `ActionBarActivity` has been deprecated for so long now that this shouldn't pose a major issue.  

Besides, it was impossible to use the newer support libraries with RxUI with the linker enabled because it would fail to resolve `ActionBarActivity`. This is now solved.

**Comment by kentcb** [comment]
gods, looks like this was a nightmare. Thanks @ghuntley and @Qonstrukt!

**Pull request merged**
