### PR TITLE
test: use new threads explicitly in message bus test

### PR DESCRIPTION
**Pull request by olevett**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Changes a test that sometimes goes 💥 

**What is the current behavior? (You can also link to an open issue here)**
MessageBus test sometimes doesn't do what's expected, because using tasks doesn't necessarily make any guarantees about threading,

**What is the new behavior (if this is a feature change)?**
Explicitly use a new thread, which should make sure things happen as we'd expected.

**What might this PR break?**
Nothing.

**Please check if the PR fulfills these requirements**
- [x] The commit follows our guidelines: https://github.com/reactiveui/reactiveui#contribute
- [x] Tests for the changes have been added (for bug fixes / features)

**Other information**:
Spotted in #1470 but I don't think it's a unique scenario.

### CODE REVIEW

**Comment by eatdrinksleepcode** [comment]
Nit: looks like the byte order mark got removed from the first line? Not sure if this repo cares about such things.

Other than that, 👍

**Comment by olevett** [comment]
Am going to assume BOM isn't too important right now, as it's not consistent across the code base anyway,

**Comment by ghuntley** [comment]
@eatdrinksleepcode come join us in Slack. We would love to have you. Https://ReactiveUI.net/slack

**Comment by ghuntley** [comment]
@eatdrinksleepcode removing BOM is okay and the way, it's remenants before we had .editorconfig/started efforts to standardise.

**Pull request merged**
