### PR TITLE
feature: add code snippets for VS, VS4Mac and Rider

### PR DESCRIPTION
**Pull request by jonstodle**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Feature, kind of

**What is the current behavior? (You can also link to an open issue here)**
Relates to: "official" visual studio/resharper code snippets #1051

**What is the new behavior (if this is a feature change)?**
Snippets for adding this.Bind, this.OneWayBind, this.BindCommand and a get/set RxUI property. Also a bit of organizing of the snippets

**What might this PR break?**
I believe nothing

**Please check if the PR fulfills these requirements**
- [x] The commit follows our guidelines: https://github.com/reactiveui/reactiveui#contribute
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by jonstodle** [comment]
If you don't mind, I'd like to give it a try myself. I'll poke you in the Slack channel if I hit any hurdles

**Comment by olevett** [comment]
👍 happy to help if you run in to anything

**Comment by ghuntley** [comment]
@olevett as maintainers we can retarget which branch a PR lands against via

image

**Comment by ghuntley** [comment]
@jonstodle thank-you for your PR!

**Pull request merged**
