### PR TITLE
tests Binding to List test

### PR DESCRIPTION
**Pull request by ChrisPulman**
Added Bind to List test with ReadOnlyObservableCollection
put solution items into two folders, Src and Tests

**What kind of change does this PR introduce?**

test

**What is the current behaviour?**

**What is the new behaviour?**

added test

**What might this PR break?**

none expected

**Please check if the PR fulfils these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by glennawatson** [comment]
An issue with this one is SourceList is not meant to be exposed to the UI layer at all. Its fundamnetally against the way DD works.

**Comment by glennawatson** [comment]
Why use a SourceList<T> directly is the other concern I have, it's meant to be for data which you observe, transform, filter etc.

**Comment by ChrisPulman** [comment]
Ok, I will rethink this to try a different approach

**Comment by ChrisPulman** [comment]
0.02% hmmm every little helps I guess

**Review by glennawatson — APPROVED** [review]

**Pull request merged**
