### PR TITLE
Remove build.sh

### PR DESCRIPTION
**Pull request by eatdrinksleepcode**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Build fix

**What is the current behavior? (You can also link to an open issue here)**

```build.sh``` is not currently supported (see [#1465](https://github.com/reactiveui/ReactiveUI/pull/1465#issuecomment-327377549)):
> Currently, the only end-to-end way for all platforms to build ReactiveUI is on
Windows via build.cmd.

**Please check if the PR fulfills these requirements**
- [x] The commit follows our guidelines: https://github.com/reactiveui/reactiveui#contribute
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by eatdrinksleepcode** [comment]
There was an unrelated test failure:
```
ReactiveUI.Tests.MessageBusTest.MessageBusThreadingTest [FAIL]
      Assert.NotEqual() Failure
      Expected: Not 5
      Actual:   5
      Stack Trace:
        src\ReactiveUI.Tests\MessageBusTest.cs(133,0): at ReactiveUI.Tests.MessageBusTest.<MessageBusThreadingTest>d__5.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

That doesn't look like a stack trace that I would expect from a normal assertion failure...

**Comment by olevett** [comment]
That is a little odd, I think the assertion is because we're in an async test.

**Comment by eatdrinksleepcode** [comment]
Yeah you're right, the location of the assert is the first line of the stack trace and the rest is just because it's an async test.

I can't run the test itself (I'm not on Windows), but looking at the code, I'm not entirely sure that line 132 is valid:
```
Assert.NotEqual(listenedThread.Value, thisThread);
```
I don't think there is anything guaranteeing that the listened thread _couldn't_ end up being the same managed thread that the test was started on.

**Comment by olevett** [comment]
Agreed, it's quite a brittle test - I think there's a better way to achieve the same thing, but separate PR, and I don't think removing an unused build script is likely to have any impact!

**Pull request merged**
