### PR TITLE
housekeeping: updated docs to Anaïs Betters

### PR DESCRIPTION
**Pull request by dukesta3**
did a search for betts and updated README.md, and multiple *.build.props folders.

**What kind of change does this PR introduce?**

Fixes documentation to show Anaïs Betts

**What is the current behavior?**

Some spots don't show Anaïs Betts

**What is the new behavior?**

N/A

**What might this PR break?**
Shouldn't break anything, but there could be some more spots that need to be updated.

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by glennawatson** [comment]
Thanks @dukesta3

**Comment by ghuntley** [comment]
How considerate of you 🥰

**Comment by glennawatson** [comment]
Might be worth doing a similar search on the website project if you can

**Comment by dukesta3** [comment]
@ghuntley - Literally the least I could do.  Ana has been a hero of mine for many years.

**Comment by glennawatson** [comment]
Made a task for the website Project https://github.com/reactiveui/website/issues/326 I will do it tomorrow if no one else does

**Pull request merged**
