### PR TITLE
Fix #1259

### LINKED ISSUE #1259: bug: the assembly for Xamarin.Mac20 in the reactiveui-events NuGet package is not included
Rather than fixing this one myself, I'm leaving this one available for the someone in the community to resolve. Preferably someone who has not done a pull-request to the project before.

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

It appears that assembly for `Xamarin.Mac20` in the `reactiveui-events` NuGet package is not included.

https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI-Events.nuspec#L31-L33

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

v7.0.0 -> v7.1.0 -> now

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

You'll need Visual Studio 2015 with Xamarin and Android API24 Installed; _you won't be able to resolve this on a Mac!_ (crazy huh!)

* Clone this repository
* Create a new branch
* Uncomment this https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI-Events.nuspec#L31-L33
* Run ./build.cmd
* Commit & Push your branch
* Send in a pull-request

### PR DESCRIPTION
**Pull request by ajpinedam**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Bug fix

**What is the current behavior? (You can also link to an open issue here)**

https://github.com/reactiveui/ReactiveUI/issues/1259

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

No

**Please check if the PR fulfills these requirements**
- [x] The commit follows our guidelines: https://github.com/reactiveui/reactiveui#contribute
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by kentcb** [comment]
This lgtm @ajpinedam - thanks. However, it's hard for me to verify the resultant NuGet packages until an unrelated issue is fixed with AppVeyor artefacts (which @ghuntley is investigating). Once I can confirm, happy to merge this 👍

**Comment by b-straub** [comment]
The nugget package creation failed because you missed to fix the document file naming. Please see my working fix for the same issue #1280.

Suggest to use the windows commandline build system (build.cmd) to verify such kind of problems in advance.

**Comment by ajpinedam** [comment]
@b-straub I will check into this and correct it accordingly. Thanks

**Comment by b-straub** [comment]
#1280 is a superset of this request since also fixing the build on Xamarin Studio for all Xamarin.Mac projects. I think only one request should remain. I don't mind to close mine but the build system fixes included should not be lost.

**Comment by ajpinedam** [comment]
@b-straub didn't add the other changes as they refer to #1175 as you indicated in your PR. Also I read in the #1175 the latest comment and was not clear if we actually should remove the **'$(OS)' == 'Windows_NT'**

**Comment by b-straub** [comment]
@ajpinedam you are right I coupled to unrelated issues. I will create a new pull request for the XS build fixes and close my request.

Indeed $(OS)' == 'Windows_NT' can be removed for all Mac projects. Hereafter the projects can build using XS, VS and Windows command line.

**Comment by b-straub** [comment]
Created a pull request for the build fixes only #1287

**Comment by kentcb** [comment]
This has been fixed (see latest package on MyGet).

**Pull request closed without merging**
