### PR TITLE
chore: split platform registrations into platform specific files

### LINKED ISSUE #1337: shared/Registrations.cs should be split by project target
This follows on from #1332 

**Do you want to request a *feature* or report a *bug*?**
Feature (ish)

**What is the current behavior?**
Multiple ifdefs are included in `src\ReactiveUI\shared\Registrations.cs`

**What is the expected behavior?**
Multiple ifdefs are included in `src\ReactiveUI\shared\Registrations.cs`

**What is the motivation / use case for changing the behavior?**
Given that the new project format has platform level inclusion of files, we should split the Registrations file up into platform specific code, and reduce the number of ifdefs.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
8 I guess, but not sure what the version number will actually be

### LINKED ISSUE #1338: File names should match classes
Following on from #1332, and since renaming files is easier, we should review naming and try to make things more consistent. 
In particular
- [ ] src/ReactiveUI/shared/Registrations.cs -> PlatformRegistrations.cs
- [ ] src/ReactiveUI/netstandard1.1/PortableLibraryStubs -> PlatformRegistrations.cs

### LINKED ISSUE #1339: Review comments at top of shared/Registrations.cs
Possibly resolved by #1337 and #1338, `src/ReactiveUI/shared/Registrations.cs` contains a comment about ReactiveUI.Xaml which is no longer correct or relevant. This should be removed.

### PR DESCRIPTION
**Pull request by olevett**
Fixes #1337, also fixes #1338 and closes #1339

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

**What is the current behavior? (You can also link to an open issue here)**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?**

**Please check if the PR fulfills these requirements**
- [ ] The commit follows our guidelines: https://github.com/reactiveui/reactiveui#contribute
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by ghuntley** [comment]
Hmmm; what about `winforms` (which is NET45 without net45 reference)

**Comment by olevett** [comment]
I think there's a file under ReactiveUI.Winforms that handles it, will check it's consistent though...

**Comment by olevett** [comment]
This needs a bit of a rework now, following the WPF change...will take a look now :)

**Comment by olevett** [comment]
Couple of additional changes
- added a net45 platform registrations file
- removed the "shared" platform registrations file (something with a rebase I think?)
- added the .Net Foundation headers

**Comment by ghuntley** [comment]
Thank-you @olevett

**Pull request merged**
