### PR TITLE
ActOnEveryObject<T> can accept IReadOnlyReactiveCollection<T>

### PR DESCRIPTION
**Pull request by arkein**
Enhancement for #989 
(this should target the proper branch now, previous PR was #999)

### CODE REVIEW

**Comment by kentcb** [comment]
I think you might have missed my comment on the previous PR. `IReadOnlyReactiveCollection` extends `IReactiveCollection`, so you've actually _narrowed_ the utility of this method by taking `IReadOnlyReactiveCollection` rather than just `IReactiveCollection`. Do you agree @flagbug ?

**Comment by flagbug** [comment]
@kentcb is right, I thought the implementation was the other way around, so extending `IReactiveCollection` is the right way to go

**Comment by shiftkey** [comment]
:thumbsup: `IReactiveCollection`

**Comment by arkein** [comment]
Read, facepalmed, fixed. I guess there's no more room left to do another mistake.

**Comment by kentcb** [comment]
Thanks @arkein!

**Pull request merged**
