### PR TITLE
Marking Observable properties from ReactiveObject and ReactiveRecord …

### LINKED ISSUE #3694: [Bug]: Mark ReactiveObject IObservable properties with DisplayAttribute for Winforms
### Describe the bug 🐞

When binding a model class into databinding controls like DevExpress ones in WinForms, because it does not implement **DisplayAttribute** from **System.Component.DataAnnotations** with **Order** set to **-1**, automatically is binding those IObservable properties from ReactiveObject and you manually need to remove them every time you bind new objects. Actually those properties are implementing two attributes: **IgnoreDataMember** and **JsonIgnore**.

Properties are:

- **Changing** 
- **Changed** 
- **ThrownExceptions** 

### Step to reproduce

1. Create a form and include a Grid control
2. Bind to that control a BindingSource mapping to the class that implements ReactiveObject class
3. Bind data to that BindingSource
4. Start the app and see that grid control is showing by default those properties because they're not implementing DisplayAttribute

### Reproduction repository

_No response_

### Expected behavior

When those properties are fixed, by default should ignore those properties for databinding.

### Screenshots 🖼️

image

### IDE

Visual Studio 2022, Visual Studio 2019, Visual Studio 2017

### Operating system

Windows

### Version

_No response_

### Device

_No response_

### ReactiveUI Version

_No response_

### Additional information ℹ️

I don't know if other frameworks like WPF are affected with this behavior.

This is the DevExpress documentation around the use of Data Annotations attributes:

https://docs.devexpress.com/WindowsForms/18273/common-features/data-binding/data-annotation-attributes

### PR DESCRIPTION
**Pull request by Micha-kun**
…as no browsable, no displayable, no autogenerateable and no autofilterable for Winforms control databindings (and possibly for WPF controls too)

Fixes #3694 

**What kind of change does this PR introduce?**
Assign new attributes on Observable properties for better hiding from Winforms/WPF

**What is the current behavior?**
Those properties are autogenerated as controls

**What is the new behavior?**
Those properties are ignored as controls

**What might this PR break?**

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Review by glennawatson — APPROVED** [review]

**Comment by Micha-kun** [comment]
What's failing? I didn't touch any test :/

Thnxs

**Comment by ChrisPulman** [comment]
> What's failing? I didn't touch any test :/
> 
> Thnxs

You need to run the tests and update the API verified files, the following needs to be added, but you just need to copy the discovered to the verified to complete this task
```
[System.ComponentModel.Browsable(false)]
[System.ComponentModel.DataAnnotations.Display(AutoGenerateField=false, AutoGenerateFilter=false, Order=-1)]
```
and 
```
namespace XamlGeneratedNamespace
{
    public sealed class GeneratedInternalTypeHelper : System.Windows.Markup.InternalTypeHelper
    {
        public GeneratedInternalTypeHelper() { }
        protected override void AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler) { }
        protected override System.Delegate CreateDelegate(System.Type delegateType, object target, string handler) { }
        protected override object CreateInstance(System.Type type, System.Globalization.CultureInfo culture) { }
        protected override object GetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, System.Globalization.CultureInfo culture) { }
        protected override void SetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, object value, System.Globalization.CultureInfo culture) { }
    }
```

**Comment by Micha-kun** [comment]
> > What's failing? I didn't touch any test :/
> > Thnxs
> 
> You need to run the tests and update the API verified files, the following needs to be added, but you just need to copy the discovered to the verified to complete this task
> 
> ```
> [System.ComponentModel.Browsable(false)]
> [System.ComponentModel.DataAnnotations.Display(AutoGenerateField=false, AutoGenerateFilter=false, Order=-1)]
> ```
> 
> and
> 
> ```
> namespace XamlGeneratedNamespace
> {
>     public sealed class GeneratedInternalTypeHelper : System.Windows.Markup.InternalTypeHelper
>     {
>         public GeneratedInternalTypeHelper() { }
>         protected override void AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler) { }
>         protected override System.Delegate CreateDelegate(System.Type delegateType, object target, string handler) { }
>         protected override object CreateInstance(System.Type type, System.Globalization.CultureInfo culture) { }
>         protected override object GetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, System.Globalization.CultureInfo culture) { }
>         protected override void SetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, object value, System.Globalization.CultureInfo culture) { }
>     }
> ```

Where are the API verified files to update? Sorry, it's my first time and don't know how to do this :)

image

This page says it should exist some file called **APIApprovals.{TestName}.approved.txt** as replaceable, where are they found? Where to put the replacement?

Thanks

**Comment by ChrisPulman** [comment]
> > > What's failing? I didn't touch any test :/
> > > Thnxs
> > 
> > 
> > You need to run the tests and update the API verified files, the following needs to be added, but you just need to copy the discovered to the verified to complete this task
> > ```
> > [System.ComponentModel.Browsable(false)]
> > [System.ComponentModel.DataAnnotations.Display(AutoGenerateField=false, AutoGenerateFilter=false, Order=-1)]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > namespace XamlGeneratedNamespace
> > {
> >     public sealed class GeneratedInternalTypeHelper : System.Windows.Markup.InternalTypeHelper
> >     {
> >         public GeneratedInternalTypeHelper() { }
> >         protected override void AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler) { }
> >         protected override System.Delegate CreateDelegate(System.Type delegateType, object target, string handler) { }
> >         protected override object CreateInstance(System.Type type, System.Globalization.CultureInfo culture) { }
> >         protected override object GetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, System.Globalization.CultureInfo culture) { }
> >         protected override void SetPropertyValue(System.Reflection.PropertyInfo propertyInfo, object target, object value, System.Globalization.CultureInfo culture) { }
> >     }
> > ```
> 
> Where are the API verified files to update? Sorry, it's my first time and don't know how to do this :)
> 
> image
> 
> This page says it should exist some file called **APIApprovals.{TestName}.approved.txt** as replaceable, where are they found? Where to put the replacement?
> 
> Thanks

For me I use VS Code, when the test's run, VS Code launches with a Compare window, the left is discovered and the right verified, copy the contents of the discovered into the verified to make identical and save, run the tests again and all should pass

**Comment by ChrisPulman** [comment]
If your still unable to get the test's to pass, I could create a branch for you to cherry pick from with the changes

**Comment by Micha-kun** [comment]
Ok, updated verified files!

**Comment by Micha-kun** [comment]
YYESS!

**Pull request merged**
