### PR TITLE
Add ReactiveUserControl<ViewModel> helper class

### LINKED ISSUE #348: Create Generic ReactiveUserControl<ViewModel>
Even though generic view classes are a bit of a pain in WPF they can be done and this class adds some very nice behaviors.

```
using ReactiveUI.Ext;
using System;
using System.Windows;
using System.Windows.Controls;
using System.Reactive.Linq;
using System.Windows.Media;
using System.Reactive.Disposables;
using System.Windows.Markup;
using System.Windows.Controls.Primitives;

namespace ReactiveUI
{
    [ContentProperty("AdditionalContent")]
    public class ReactiveUserControl<ViewModelT> : UserControl, IViewFor<ViewModelT>
        where ViewModelT : class 
    {
        #region IViewFor<ViewModelT>
        public static readonly DependencyProperty ViewModelProperty =
            DependencyProperty.Register("ViewModel", typeof(ViewModelT), typeof(ReactiveUserControl<ViewModelT>), new PropertyMetadata(null));

        public ViewModelT ViewModel
        {
            get { return (ViewModelT)GetValue(ViewModelProperty); }
            set { SetValue(ViewModelProperty, value); }
        }

        object IViewFor.ViewModel
        {
            get { return (ViewModelT)GetValue(ViewModelProperty); }
            set { SetValue(ViewModelProperty, value); }
        }
        #endregion

        /// <summary>
        /// Gets or sets additional content for the UserControl. The additional
        /// content will have it's DataContext set to an instance of the ViewModel
        /// </summary>
        public UIElement AdditionalContent
        {
            get { return (UIElement)GetValue(AdditionalContentProperty); }
            set { SetValue(AdditionalContentProperty, value); }
        }

        public static readonly DependencyProperty AdditionalContentProperty =
            DependencyProperty.Register("AdditionalContent", typeof(UIElement), typeof(ReactiveUserControl<ViewModelT>),
              new PropertyMetadata(null));

        public IObservable<ViewModelT> ViewModelObservable()
        {
            return this.WhenAny(x => x.ViewModel, x => x.Value)
                .Where(v=>v!=null);
        }

        public UniformGrid DataContextHost { get; private set; }

        public ReactiveUserControl()
        {
            DataContextHost = new UniformGrid();
            this.Content = DataContextHost;

            // If AdditionalContent changes then we need to
            // add it to the visual tree
            this.WhenAny(p => p.AdditionalContent, p => p.Value)
                .Where(v=>v!=null)
                .Subscribe(v => {
                    DataContextHost.Children.Clear();
                    DataContextHost.Children.Add(v);
                });

            // If the ViewModel changes we need to ensure the
            // AdditionalContent get's the correct DataContext
            this.WhenAny(x => x.ViewModel, x => x.Value)
                .BindTo(this, x=>x.DataContextHost.DataContext);

            DesignUnsafeConstruct();
            if (!System.ComponentModel.DesignerProperties.GetIsInDesignMode(this))
            {

                DesignSafeConstruct();

            }
        }

        public virtual void DesignUnsafeConstruct(){
        }

        public virtual void DesignSafeConstruct(){
        }
    }

    public static class ReactiveUserControlMixins
    {
        // Dispose the previous disposable when the next is registered
        // and then dispose the last one when the UI is shut down
        public static void SeriallyDisposeWith(this IObservable<IDisposable> This, Control control)
        {
            var disposer = new SerialDisposable();
            This.Subscribe(d=>disposer.Disposable=d);
            control.Unloaded += (s, e) => disposer.Dispose();
            control.Dispatcher.ShutdownStarted += (s, e) => disposer.Dispose();
        }

        // Dispose when unloaded or dispatcher is shut down
        public static void DisposeWith(this IDisposable This,  Control contrl)
        {
            contrl.Unloaded += (s, e) => This.Dispose();
            contrl.Dispatcher.ShutdownStarted += (s, e) => This.Dispose();
        }
    }

}
```

Usage is something like

```
namespace WeinCad.Controls.View
{
    public class MoineauMillingViewBase : ReactiveUserControl<MoineauMillingViewModel> { }
    /// <summary>
    /// Interaction logic for MoineauMillingView.xaml
    /// </summary>
    public partial class MoineauMillingView : MoineauMillingViewBase
    {
        public MoineauMillingView()
        {
            InitializeComponent();
        }
    }
}
```

and in XAML

```
<l:MoineauMillingViewBase x:Class="WeinCad.Controls.View.MoineauMillingView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:l="clr-namespace:WeinCad.Controls.View"
             mc:Ignorable="d" 
             d:DesignHeight="300" d:DesignWidth="300">
    <Grid>
        <Label>Moin Moin Milling</Label>

    </Grid>
</l:MoineauMillingViewBase>
```

The reactiveuser control wraps internal content in a hidden control on which the datacontext is set to the ViewModel. This automatically protects the internal DataContext from being set if a user directly sets the DataContext on an instance of the control.

There are also some helpers for managing IDisposable lifetimes in terms of load and unload events.

It's not a pull request as I have this code internal to my codebase but if you like I'll take the effort to make a patch

### PR DESCRIPTION
**Pull request by bradphelan**
Fixes #348

### CODE REVIEW

**Comment by tlycken** [comment]
Did this PR just die out of low interest, or has it been worked with elsewhere? I've come to need this functionality too, so I'd be very interested in seeing this merged :)

@bradphelan In the meantime, do you mind if I just copy-paste your class definition into our project to keep moving forward?

**Comment by bradphelan** [comment]
Fine by me. I'd forgotten about it. The code we use in house has probably migrated a bit since this pull request

**Comment by bradphelan** [comment]
Here's the latest code we use. Not sure if it has changed much but two years is a while.

	using System.Collections;
	using System.Collections.Generic;
	using System.Drawing;
	using System.Reactive;
	using System.Windows.Media;
	using ReactiveUI.Ext;
	using System;
	using System.Reactive.Disposables;
	using System.Reactive.Linq;
	using System.Windows;
	using System.Windows.Controls;
	using System.Windows.Controls.Primitives;
	using System.Windows.Markup;
	using Weingartner.Lens;
	using Color = System.Windows.Media.Color;
	
	namespace ReactiveUI
	{
	    /// <summary>
	    /// A generic control for wrapping up the concept of a View that has a ViewModel.
	    /// Due to XAML not being friendly for generic types it is recommended to use the 
	    /// following pattern
	    /// 
	    ///    namespace BradsAwsomeNamespace
	    ///    {
	    ///        public class BradViewModel : ReactiveObject {
	    ///             string _Name;
	    ///             public string Name 
	    ///             {
	    ///                 get { return _Name; }
	    ///                 set { this.RaiseAndSetIfChanged(ref _Name, value); }
	    ///             }
	    ///             string _PhoneNumber;
	    ///             public string PhoneNumber 
	    ///             {
	    ///                 get { return _PhoneNumber; }
	    ///                 set { this.RaiseAndSetIfChanged(ref _PhoneNumber, value); }
	    ///             }
	    ///        }
	    ///
	    ///        public class BradViewBase : ReactiveUserControl<BradViewModel> { }
	    ///        public partial class BradView : BradViewBase
	    ///        {
	    ///            public BradView()
	    ///            {
	    ///                InitializeComponent();
	    ///            }
	    ///        }
	    ///    }
	    ///
	    /// and then in XAML do
	    /// 
	    ///    <l:BradViewBase x:Class="WeinCad.Controls.View.MoineauMillingView"
	    ///             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	    ///             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	    ///             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
	    ///             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
	    ///             xmlns:l="clr-namespace:WeinCad.Controls.View"
	    ///             mc:Ignorable="d" 
	    ///             d:DesignHeight="300" d:DesignWidth="300">
	    ///         <Grid>
	    ///             <Label Content={Binding Name}/>
	    ///             <Label Content={Binding PhoneNumber}/>
	    ///         </Grid>
	    ///    </l:BradViewBase>
	    ///
	    /// and use your new control like
	    /// 
	    ///     <DataTemplate>
	    ///         <c:BradView ViewModel={Binding BradviewModel}/>
	    ///     </DataTemplate>
	    ///
	    /// There are also helper methods to manage lifetimes of IDisposableResources. For example
	    /// you may wish in your code behind to register to a timer but dispose of it when the
	    /// user control is no longer used. Using ReactiveUserControl this is easy.
	    /// 
	    ///     _Counter = Observable.Interval(TimeSpan.Seconds(1))
	    ///         .ToProperty(this, p => p.Counter);
	    ///         
	    ///     _Counter.DisposeWith(this);
	    ///     
	    /// Now the _Counter will be disposed when the control is unloaded or the
	    /// dispatcher is shut down. 
	    /// 
	    ///
	    /// Also note that the DataContext within the XAML associated with the user
	    /// control is not the same as the DataContext of the user control when it
	    /// is inserted into client XAML. For the purposes of sanity the DataContext
	    /// inside the user control is the ViewModel instance. If a user of the
	    /// user control manually sets the DataContext as in
	    /// 
	    ///     <c:BradView DataContext={Binding FooPath} ViewModel={Binding Model}/>
	    ///     
	    /// which is effectively the same thing as
	    ///
	    ///     <c:BradView ViewModel={Binding Path=FooPath.Model}/>
	    ///     
	    /// has no effect on the DataContext inside the XAML defining the BradView
	    /// which will always remain the ViewModel instance.
	    ///     
	    /// </summary>
	    /// <typeparam name="ViewModelT"></typeparam>
	    [ContentProperty("AdditionalContent")]
	    public class ReactiveUserControl<ViewModelT> : UserControl, IViewFor<ViewModelT>
	        where ViewModelT : class
	    {
	        #region IViewFor<ViewModelT>
	        public static readonly DependencyProperty ViewModelProperty =
	            DependencyProperty.Register("ViewModel", typeof(ViewModelT), typeof(ReactiveUserControl<ViewModelT>), new PropertyMetadata(null));
	
	        public ViewModelT ViewModel
	        {
	            get { return ( ViewModelT ) GetValue(ViewModelProperty); }
	            set { SetValue(ViewModelProperty, value); }
	        }
	
	        object IViewFor.ViewModel
	        {
	            get { return ( ViewModelT ) GetValue(ViewModelProperty); }
	            set { SetValue(ViewModelProperty, value); }
	        }
	        #endregion
	
	        /// <summary>
	        /// Gets or sets additional content for the UserControl. The additional
	        /// content will have it's DataContext set to an instance of the ViewModel
	        /// </summary>
	        public UIElement AdditionalContent
	        {
	            get { return ( UIElement ) GetValue(AdditionalContentProperty); }
	            set { SetValue(AdditionalContentProperty, value); }
	        }
	
	        public static readonly DependencyProperty AdditionalContentProperty =
	            DependencyProperty.Register("AdditionalContent", typeof(UIElement), typeof(ReactiveUserControl<ViewModelT>),
	              new PropertyMetadata(null));
	
	        public IObservable<ViewModelT> ViewModelObservable()
	        {
	            return this.WhenAnyValue(x => x.ViewModel)
	                .Where(v => v != null);
	        }
	
	        public UniformGrid DataContextHost { get; private set; }
	
	        public ReactiveUserControl()
	        {
	            DataContextHost = new UniformGrid();
	            this.Content = DataContextHost;
	            AdditionalContent = new UIElement();
	
	            // If AdditionalContent changes then we need to
	            // add it to the visual tree
	            this.WhenAnyValue(p => p.AdditionalContent)
	                .Where(v => v != null)
	                //.ObserveOn(RxApp.MainThreadScheduler)
	                .Subscribe(v =>
	                {
	                    DataContextHost.Children.Clear();
	                    DataContextHost.Children.Add(v);
	                });
	
	            // If the ViewModel changes we need to ensure the
	            // AdditionalContent get's the correct DataContext
	            this.WhenAnyValue(x => x.ViewModel)
	                //.ObserveOn(RxApp.MainThreadScheduler)
	                .BindTo(DataContextHost, x => x.DataContext);
	
	            DesignUnsafeConstruct();
	            if ( !System.ComponentModel.DesignerProperties.GetIsInDesignMode(this) )
	            {
	
	                DesignSafeConstruct();
	
	            }
	        }
	
	        public virtual void DesignUnsafeConstruct()
	        {
	        }
	
	        public virtual void DesignSafeConstruct()
	        {
	        }
	    }
	
	    public static class ReactiveUserControlMixins
	    {
	        public static void LoadUnloadHandler(this FrameworkElement control, Func<IEnumerable<IDisposable>> action)
	        {
	            LoadUnloadHandler(control, () => (IDisposable) new CompositeDisposable(action()));
	        }
	
	        public static void LoadUnloadHandler(this FrameworkElement control, Func<IDisposable> action)
	        {
	            bool state = false;
	            var cleanup = Disposable.Empty;
	            Observable.Merge
	                ( control.Events().Loaded.Select(x => true)
	                , control.Events().Unloaded.Select(x => false)
	                )
	                .Subscribe(isLoadEvent =>
	                {
	                    if (!state)
	                    {
	                        // unloaded state
	                        if (isLoadEvent)
	                        {
	                            state = true;
	                            cleanup = action();
	                        }
	                    }
	                    else
	                    {
	                        // loaded state
	                        if (!isLoadEvent)
	                        {
	                            state = false;
	                            cleanup.Dispose();
	                        }
	                    }
	
	                });
	        }
	
	
	        public static void LoadUnloadHandler<T>(this IObservable<T> @this, FrameworkElement control, Action<T> action)
	        {
	            LoadUnloadHandler(control, ()=>@this.Subscribe(action));
	        }
	
	
	        public static IDisposable SubscribeDisposable<T>
	            ( this IObservable<T> observable
	            , Func<T,IDisposable> action
	            )
	        {
	            var d = Disposable.Empty;
	            return observable
	                .Finally(() => d.Dispose())
	                .Subscribe
	                (e =>
	                 {
	                     d.Dispose();
	                     d = action(e);
	                 });
	        }
	
	        public static IDisposable SubscribeDisposable<T>
	            ( this IObservable<T> observable
	            , Func<T,IEnumerable<IDisposable>> action)
	        {
	            return SubscribeDisposable( observable , t => ( IDisposable ) new CompositeDisposable(action(t)));
	        }
	    }
	
	
	    public class LensUserControl<ViewModelT> : ReactiveUserControl<ILens<ViewModelT>>
	    {
	        public override void DesignUnsafeConstruct(){
	            ViewModel = Lens.Empty<ViewModelT>();
	        }
	    }
	
	    public class ReactiveWindow<ViewModelT> : Window, IViewFor<ViewModelT>
	        where ViewModelT : class 
	    {
	        #region IViewFor<ViewModel>
	        public static readonly DependencyProperty ViewModelProperty =
	            DependencyProperty.Register("ViewModel", typeof(ViewModelT), typeof(ReactiveUserControl<ViewModelT>), new PropertyMetadata(null));
	
	        public ViewModelT ViewModel
	        {
	            get { return (ViewModelT)GetValue(ViewModelProperty); }
	            set { SetValue(ViewModelProperty, value); }
	        }
	
	        object IViewFor.ViewModel
	        {
	            get { return (ViewModelT)GetValue(ViewModelProperty); }
	            set { SetValue(ViewModelProperty, value); }
	        }
	        #endregion
	
	        public ReactiveWindow()
	        {
	            this.WhenAnyValue(x => x.ViewModel)
	                .BindTo(this, x => x.DataContext);
	        }
	    }
	}

**Comment by tlycken** [comment]
Thanks a lot! :+1:

Now I just have to figure out how best to make use of it ;)

**Comment by bradphelan** [comment]
The only hacky thing is that generics in XAML kinda suck. So it's best to create a non generic base and then inherit your main control fromthat.

    ///        public class BradViewBase : ReactiveUserControl<BradViewModel> { }
    ///        public partial class BradView : BradViewBase
    ///        {
    ///            public BradView()
    ///            {
    ///                InitializeComponent();
    ///            }
    ///        }
    
see the doc at the top of the class. Let me know if you have any troubles. We use it in about 30 production views so it's been battle tested :)

**Comment by bradphelan** [comment]
And disregard the class


	    public class LensUserControl<ViewModelT> : ReactiveUserControl<ILens<ViewModelT>>
	    {
	        public override void DesignUnsafeConstruct(){
	            ViewModel = Lens.Empty<ViewModelT>();
	        }
	    }
	    
You don't need that.

**Comment by tlycken** [comment]
Thanks for the updates :)

Unfortunately, I can't even get the class to build. I assume it's because I'm using it in a project for Windows Phone 8.1, and it's targeted at another platform?

I can make some simple changes (remove unused `using`s that don't compile, import some new classes that R# suggests, remove the argument to `[ContentProperty]` on the class) to get most of the errors to disappear, but there are still a few things I don't know how to handle:

```
// UniformGrid is not defined (line 147)
public UniformGrid DataContextHost { get; private set; }
```

and

```
// DesignerProperties isn't defined (line 173)
if (!System.ComponentModel.DesignerProperties.GetIsInDesignMode(this))
{
    DesignSafeConstruct();
}
```

and

```
// .Events is not defined (line 202)
Observable.Merge
    (control.Events().Loaded.Select(x => true)
    , control.Events().Unloaded.Select(x => false)
)
```

For the first one, can I just replace `UniformGrid` with `Grid`? If not, what do I do? For the second, I think I can just delete the entire check, since both the called methods are empty, but what do I do about the third?

Thanks a lot for all your help!

**Comment by bradphelan** [comment]
Yeah, It's targeting a WPF usercontrol so you may find you need to modify for win 8.1 phone. UniformGrid is definately WPF. You could replace it with anything that will hold a child. There must be some kind of grid control in the standard toolbox you are using.

The DesignSafeConstruct pattern is something you can just remove if you want. It just a simple way to detect if the designer is running and not run the body of that function. Either find another detection mechanism for win 8.1 or get rid of it.

.Events is more tricky. This is a library that Paul write to make the C# event system more RX friendly.  It comes from the ReactiveUI.Events library. However the implementation is pretty brute force and uses Cecil to generate extension methods for all __known__ controls. However it might be that Paul didn't provide generators for the win 8.1 phone controls. Perhapps check with him.

**Comment by kentcb** [comment]
I'm not sure I understand entirely the need for the shim base class (nor the `AdditionalContent` property). In my WPF project, I have a `ReactiveUserControl` defined as follows:

```C#
    public abstract class ReactiveUserControl<TViewModel> :
        UserControl, IViewFor<TViewModel>
        where TViewModel : class
    {
        public static readonly DependencyProperty ViewModelProperty =
            DependencyProperty.Register(
                "ViewModel",
                typeof(TViewModel),
                typeof(ReactiveUserControl<TViewModel>));

        public TViewModel ViewModel
        {
            get { return (TViewModel)this.GetValue(ViewModelProperty); }
            set { this.SetValue(ViewModelProperty, value); }
        }

        object IViewFor.ViewModel
        {
            get { return this.ViewModel; }
            set { this.ViewModel = (TViewModel)value; }
        }
    }
```

Which gets used like this:

```XML
<rxui:ReactiveUserControl
        x:Class="Namespace.Views.SomeView"
        x:TypeArguments="vms:SomeViewModel"
        ...
```

This approach has worked fine for me and I intended creating a PR for my `ReactiveUserControl` until I saw yours. Can you explain why my approach is inadequate? The only thing I can think of is Blend/designer support (which I don't use).

**Comment by bradphelan** [comment]
The reason for the AddtionalContent is to set the DataContext for the child controls to be the viewmodel. However if you set the DataContext of the ReactiveUserControl itself to be the viewmodel then it changes the datacontext for users of the final user control.

**Comment by bradphelan** [comment]
I created the shim class because I never got good results with using generics in WPF/XAML. If it works for you then cool :+1:

**Comment by kentcb** [comment]
Superseded by #943

**Pull request closed without merging**
