### PR TITLE
Update Program.cs

### PR DESCRIPTION
**Pull request by timotei**
**What kind of change does this PR introduce?**
Improvement fix :D

**What is the current behavior?**
No error logged on errors.

**What is the new behavior?**
Error logged on errors.

**What might this PR break?**
Nothing.

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by glennawatson** [comment]
Thanks for the pr but event builder is changing soon. So will be closing this one.

**Comment by glennawatson** [comment]
It's basically getting a full rewrite so will leave as is for the moment. There's also some splat extensions that can an make that logging easier.

**Comment by timotei** [comment]
@glennawatson Hmm, I think would be awesome if you could expose the eventbuilder somehow (prebuilt binary), as a nuget package for example. We want to generate the events for some DevExpress libraries but for that we have to maintain our own fork, instead of just using an existing exe (https://github.com/gluck/ReactiveUI/blob/DevExpress/ReactiveUI.Events/ReactiveUI.Events.Dx15.Xpf_Net40.csproj)

**Comment by glennawatson** [comment]
Yeah that's the direction I am going. You can specify nuget or assembly to generate events for.

**Comment by glennawatson** [comment]
Part of the motivation for the rewrite we had users who were ahead on xamarin forms so their events weren't matching. So by rewriting and allowing it to be a msbuild task or global tool we can generate events for specific versions. 

I had to speed up the generation to do it so using Roslyn and system.reflection.metadata now

**Comment by timotei** [comment]
@glennawatson Btw, how about renaming the .events packages to something more proper, that does *not* include "ReactiveUI"? Cause technically, apart from the repo, they don't use anything reactiveui. 

Maybe they should be renamed to just "Reactive.Events.X". What do you think?

**Comment by glennawatson** [comment]
Worth asking about that one on slack under the #reactiveui-dev channel. 

Generally I shy away from package renames since there is quite a bit of work involved.

**Comment by glennawatson** [comment]
https://github.com/reactiveui/pharmacist is going to be released in the next 24 hours. It's the replacement for event builder.

**Comment by glennawatson** [comment]
So for the devexpress libraries, you can probably just use Pharmacist.MsBuild now, similar to what we do with Xamarin.Essentials -- I'm integrating some of @gluck performance improvements he tried to implement about 2-3 years ago now.

**Pull request closed without merging**
