### PR TITLE
ActOnEveryObject can use IReactiveCollection<T>

### PR DESCRIPTION
**Pull request by arkein**
Fix for #989

### CODE REVIEW

**Comment by ghuntley** [comment]
@flagbug can you please review?

**Comment by flagbug** [comment]
Hm, I guess we could even make it an an extensions of `IReadOnlyReactiveCollection`

**Comment by kentcb** [comment]
`IReadOnlyReactiveCollection` extends `IReactiveCollection`, so that should Just Work. Will merge this shortly if no objections.

**Comment by kentcb** [comment]
Oh wait, this is targeting the wrong branch. @arkein: any chance you could close this and re-open a new PR that targets rxui7-master?

**Comment by ghuntley** [comment]
Sorry about this @arkein, we have since switched our default branch to `rxui7-master` (aka develop in the future) so this won't happen again.

**Comment by arkein** [comment]
So, I've taken @flagbug note about `IReadOnlyReactiveCollection` in account. Target branch is corrected as well. Could you please take a look once again?

**Pull request closed without merging**
