### PR TITLE
chore: rename MobileLifecycle.cs to SuspensionHost.cs

### PR DESCRIPTION
**Pull request by olevett**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
File rename

**What is the current behavior? (You can also link to an open issue here)**
MobileLifecycle contains a class called SuspensionHost and some related helpers, without any reference to MobileLifecycle. This is covered under #1246 

**Please check if the PR fulfills these requirements**
- [x] The commit follows our guidelines: https://github.com/reactiveui/reactiveui#contribute
- [ ] Tests for the changes have been added (for bug fixes / features) - n/a
- [ ] Docs have been added / updated (for bug fixes / features) - n/a

**Other information**:

### CODE REVIEW

**Comment by olevett** [comment]
@kentcb - as discussed previously, this isn't the safest of change, given the variety of affected files - I've got builds working locally and the CI one seems to behave, so I think I've covered off all the places that should be impacted.

**Comment by olevett** [comment]
So this build has failed with 
```
Build with specified version already exists.
```
not sure quite what to do about that, but given the Coveralls build succeeded, I think it's an AppVeyor issue/something I did that broke AppVeyor...

**Comment by kentcb** [comment]
Hey @olevett. Yeah, I was trying to get this merged when things went awry. @ghuntley is looking into this.

**Comment by ghuntley** [comment]
Alright that build error has been resolved.

**Comment by kentcb** [comment]
Thanks @ghuntley. And thanks for the PR @olevett!

**Pull request merged**
