### PR TITLE
[WIP] fix: reactiveui-wpf.csproj triggers defect/crash in visual studio for windows when opening reactiveui.sln

### PR DESCRIPTION
**Pull request by ghuntley**
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

* File -> Open -> ReactiveUI.sln 💥 upon loading

error-message-after-visual-studio-crashes

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

See this entire thread https://twitter.com/onovotny/status/915908695015477248 and #1504 

# WARNING # 
This isn't fixed yet; CI will pass green and produce valid binaries but VSWIN if opened will crash.

### CODE REVIEW

**Comment by ghuntley** [comment]
When the following workaround (remove + import target) is used

```
<PropertyGroup>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
</ProperyGrouip>
```

Visual Studio no longer crashes on startup but instead opens up a treasure trove of other problems


image

**Comment by onovotny** [comment]
That looks like it's trying to reference the netstandard1.1 target in RxUI rather than the net45 one in there....weird.

@emgarten @rohit21agrawal @rrelyea @unniravindranathan any idea what's going on here?

**Comment by ghuntley** [comment]
Additional information:

* Remove `ReactiveUI.WPF`
* Remove `ReactiveUI.Events.WPF`
* Remove `ReactiveUI.Testing` ('cause it deps on reactiveui-wpf)

Then everything is fine until you add a `File -> New Net461 Class Library` and then more 💥happens 

image

**Comment by onovotny** [comment]
What if you update to the latest SourceLink. I think earlier versions brought in dependencies

**Comment by onovotny** [comment]
that last bit is because of this https://github.com/reactiveui/ReactiveUI/blob/develop/src/Directory.build.targets#L25-L27

That needs to be in a Choose/When block since the legacy project system always evaluates items

**Comment by onovotny** [comment]
Needs to be done like this: https://github.com/reactiveui/ReactiveUI/blob/develop/src/Directory.build.props#L25-L33

**Comment by onovotny** [comment]
@ghuntley that one is failing because it's not marked as a legacy project in the props. You may not need the restoreprojectstyle.

**Pull request closed without merging**
