### PR TITLE
fix: Remove UnoUI to its own repo and fix macos, maccatalyst builds and maui

### PR DESCRIPTION
**Pull request by glennawatson**
**What kind of change does this PR introduce?**

housekeeping, fix

**What is the current behavior?**

doesn't build with maui changes

**What is the new behavior?**

Changed to Carousel View.
Add Mac Catalyst targets for net6
Update various versions

**What might this PR break?**
Hopefully none

**Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by glennawatson** [comment]
hey @jeromelaban would use your help on this one. It seems to be requesting on the net6.0 mac/maccatalyst targets a reference to Xamarin.Mac. Just trying to fix up our builds.

Thanks

**Review by cabauman — APPROVED** [review]

**Comment by jeromelaban** [comment]
@glennawatson this is unfortunately a set of breaking changes coming from .NET 6 Mobile Preview 14 (`nfloat` becoming `NFloat` and `Xamarin.iOS` assembly becoming `Microsoft.iOS` among others). 

The other unfortunate part is that building on CI with that preview is amazingly complex at this time (See the [know issues](https://github.com/dotnet/maui/releases/tag/6.0.200-preview.14.2) at the end), which is why we're already building using rc1 in Uno.Check, which does not require a mix of 6.0.200 and 6.0.300-preview SDK builds.

Now, you have two options:
- Wait for later .NET Mobile Preview/RC to fix these incompatibilities
- Use uno-check temporarily to align the all the versions, until the .NET team stabilizes their workload versions. This PR (https://github.com/unoplatform/Uno.XamlBehaviors/pull/24/files) contains all the modifications/hacks needed to use this option.

**Comment by glennawatson** [comment]
Fun thankyou @jeromelaban

**Comment by jeromelaban** [comment]
I'm noticing that Uno's original error was caused by the use of Uno 4.0.x, which uses previous builds for net6. Still, the .NET team has moved to versioning net6 binaries, causing issues like [this one](https://github.com/unoplatform/uno/discussions/8453): 

```
Error CS1705 Assembly 'Uno.UI' with identity 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.iOS, Version=15.2.303.55, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
which has a higher version than referenced assembly 'Microsoft.iOS' with identity 'Microsoft.iOS, Version=15.2.302.122, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'
```

I fear that until net6 mobile is considered stable, we'll continue getting weird version issues when referencing it (even if you remove Uno from the mix).

**Comment by glennawatson** [comment]
@jeromelaban I'm moving Uno integration over to https://github.com/reactiveui/reactiveui.uno for the moment. Makes it easier to isolate issues.

**Pull request merged**
