### PR TITLE
Xamarin forms 3.0

### PR DESCRIPTION
**Pull request by vatsalyagoel**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Add Support for netstandard2.0 so that Xamarin Forms 3.0 Builds

**What is the current behavior? (You can also link to an open issue here)**
#1630 

**What is the new behavior (if this is a feature change)?**
It also looks for the .netstandard assembly location as defined in common reference assemblies location

**What might this PR break?**
It shouldn't break anything

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by ghuntley** [comment]
Thanks for jumping onto this one Vats. Will need to put the in in once again. Wont be merging this until a couple weeks / month go by. Maybe sooner. Depends on demand. I don't want to create a rift between XF2.5 to XF3.0 users. Let's give them some more time.

**Comment by ghuntley** [comment]
Opened discussion with folks re: when should ReactiveUI upgrade Xamarin.Forms over at https://github.com/reactiveui/rfcs/issues/7

**Comment by glennawatson** [comment]
I think we should bite the bullet on this one and just bump. We've had the RFC open for over a month now and seems to be the feedback there that this guy should go ahead.

**Comment by vatsalyagoel** [comment]
I'll still keep it to 3.0 event though 3.1 is released. Lets follow the same strategy as https://github.com/reactiveui/rfcs/pull/6

**Comment by glennawatson** [comment]
3.0.0.561731 is out now..

**Comment by ghuntley** [comment]
I would have preferred to wait one additional release before revving to v3.0 but I was AWOL and didn't voice any objections so you completely did the right thing with proceeding. Thanks folks for shipping this. Thank-you @vatsalyagoel for your PR.

**Comment by glennawatson** [comment]
Doh. Sorry. I sort of posted around the RFC and this task asking for feedback on slack etc, but didn't really obey "Will wait until next release"

**Pull request merged**
