### PR TITLE
stamp ReactiveUI ($(TargetFramework)) into builds

### PR DESCRIPTION
**Pull request by cabauman**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Stamp <Product>$(AssemblyName) ($(TargetFramework))</Product> into builds

**What is the current behavior? (You can also link to an open issue here)**
No stamp

**What is the new behavior (if this is a feature change)?**
Stamp <Product>$(AssemblyName) ($(TargetFramework))</Product> into builds

**What might this PR break?**
Nothing

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:
Issue: #1596

### CODE REVIEW

**Comment by ghuntley** [comment]
I'm having a look at this. I think  AssemblyName is not being defined/resolved. Best way to troubleshoot this is to take the binlog and put it in http://msbuildlog.com/

**Comment by ghuntley** [comment]
re: not pre-checking

It's all good!

re: wtf is going on

image

image

AssemblyName is set when ProductName is evaluated but it's coming out as null. Strange.

re: next steps

I'm parking this one and moving on. We'll put it in the next release. It's pretty low priority.

**Comment by Asesjix** [comment]
In most cases the project name is the same as the assembly name (all of us), then $(MSBuildProjectName) will work.. I also do not understand why AssemblyName sometimes does not work.

But why not just write "ReactiveUI ($(TargetFramework))", the product stays the same or what do you think? ;-)

**Comment by cabauman** [comment]
Yep, looks good on this end.
reactiveui stamp

**Comment by olevett** [comment]
Thanks @cabauman

**Pull request merged**
