### PR TITLE
Feature: Support for WinUI3 desktop

### PR DESCRIPTION
**Pull request by harvinders**
**What kind of change does this PR introduce?**

It adds support for WinUI 3 desktop. Will add more information as I proceed further.

**What is the current behavior?**

**What is the new behavior?**

**What might this PR break?**

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/reactiveui/ReactiveUI?pullRequest=2897) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/reactiveui/ReactiveUI?pullRequest=2897) before we can accept your contribution.<br/><br/>:x: harvinders [sign now](https://cla.dotnetfoundation.org/reactiveui/ReactiveUI?pullRequest=2897)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/reactiveui/ReactiveUI?pullRequest=2897) it.</sub>

**Comment by glennawatson** [comment]
We will merge your PR then add support for net6 version as well. 

Thanks for your help.

**Review by ChrisPulman — APPROVED** [review]

**Comment by kmgallahan** [comment]
@harvinders When I install the ReactiveUI.WinUI package I receive this error:

Screenshot 2021-10-03 135528

This is with a blank WinUI 3 desktop app created using the Windows App SDK 1.0.0-preview1 template (with no page declarations in the project files).

**Comment by harvinders** [comment]
It is maybe because Microsoft has decided to rename the nuget package for project reunion to windows app SDK in preview 1. 

ReactiveUI package would need to be complied with release version 1 to fix it.

**Comment by glennawatson** [comment]
This is why we normally never support anything that hasn't had a full release.

**Pull request merged**
