### PR TITLE
housekeeping: header incorrectly said MS-PL instead of MIT

### PR DESCRIPTION
**Pull request by ghuntley**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

house keeping

**What is the current behavior? (You can also link to an open issue here)**

Headers incorrectly say MS-PL

**What is the new behavior (if this is a feature change)?**

Headers state the correct license (MIT)

**What might this PR break?**

It was a programmatic find and replace

image

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by glennawatson** [comment]
I've opened a bug over here https://github.com/onovotny/MSBuildSdkExtras/issues/98 about the weird msbuid.sdk.extras error.

**Comment by ghuntley** [comment]
If we need to revert out that commit that updates msbuild.extras then happy to do so.

**Comment by glennawatson** [comment]
msbuild.sdk.extras changed a bit in the latest version, you now need to add additional properties to wpf/winforms applications

```Support for WPF and Windows Forms requires an opt-in property to enable: Set ExtrasEnableWpfProjectSetup/ExtrasEnableWinFormsProjectSetup to true to include required references and default items.```

This is in regards to the recent upgrade to Msbuild.sdk.extras

but the other bug isn't explained by those either though

You may want to revert that until those items can be sorted out by Oren as well.

**Comment by onovotny** [comment]
How are the extras being added? Will fix next week, but it should work as an SDK reference instead of as a PackageReference.

**Comment by glennawatson** [comment]
Yeah at the moment it's set as a ProjectReference inside the Directory.Build.Props file.

**Comment by onovotny** [comment]
I'd switch that to set the version in a global.json and then use the Sdk= attribute. 

I'll still fix the underlying issue though.

**Comment by glennawatson** [comment]
@onovotny About to submit a new PR with the change to the newer format. Seemed to have solved those issues.

**Comment by glennawatson** [comment]
See https://github.com/reactiveui/ReactiveUI/pull/1695 implemented your recommendations.

**Pull request merged**
