### PR TITLE
Add example of custom view location

### PR DESCRIPTION
**Pull request by kmcginnes**
This feature was confusing, because it was not obvious that ReactiveUI was not accepting my `IViewLocator` because it was registering its own internal `DefaultViewLocator` after I registered mine.

Finding out about `Locator.CurrentMutable.InitializeSplat()` and `Locator.CurrentMutable.InitializeReactiveUI()` was key.

### CODE REVIEW

**Comment by kmcginnes** [comment]
And I couldn't figure out how to add this information to the official "read the docs" area. So if there's an easy enough way for me to do that, then I'm game.

**Comment by ghuntley** [comment]
:+1:  thanks.

The documentation now lives over at https://github.com/reactiveui/documentation - don't fret - I'll move your contribution over to there. Come join us in Slack and we will add you to the documentation repo which will make future contributions super easy.

**Comment by ghuntley** [comment]
https://github.com/reactiveui/reactiveui#slack

**Comment by kmcginnes** [comment]
Invite request sent. Thank you @ghuntley !

**Pull request merged**
