### PR TITLE
Xamarin.Android.Support package reference versions increased to 28.*

### PR DESCRIPTION
**Pull request by arda-a**

### CODE REVIEW

**Comment by glennawatson** [comment]
Hey, 

Thanks for the PR, our official policy is to be one version behind the latest in terms of Xamarin based technology, see our rationale here https://github.com/reactiveui/rfcs/issues/7

It shouldn't stop you from using the 28.* series of NuGet packages though, just explicitly include the PackageReference in your application until we adopt.

**Comment by arda-a** [comment]
Hi @glennawatson , thanks for the info. I wasn't aware of that policy, sorry about that.

**Comment by glennawatson** [comment]
It's all good, thanks for contributing anyway. If you have any further stuff you want to submit you can always open an issue, we are pretty fast to respond, that way you know if you are wasting your time or not. Happy to have new contributors.

**Comment by arda-a** [comment]
Good to know. Will do that, thanks again.

**Pull request closed without merging**
