### PR TITLE
Remove superfluous AsObservable calls from ReactiveCommand

### LINKED ISSUE #1236: perf: remove superfluous AsObservable calls in ReactiveCommand
**Do you want to request a *feature* or report a *bug*?**

Code issue.

**What is the current behavior?**

`ReactiveCommand` includes several properties that return observables, but calls `AsObservable` on those return values.

**What is the expected behavior?**

There is no need to call `AsObservable` - it only adds to the performance cost by creating another object on top of the already-usable observable.

**What is the motivation / use case for changing the behavior?**

Better code and performance.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

7

### PR DESCRIPTION
**Pull request by kentcb**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Correctness/performance improvement. Fixes #1236.

**What is the current behavior? (You can also link to an open issue here)**

`ReactiveCommand` includes a couple of unnecessary calls to `AsObservable`.

**What is the new behavior (if this is a feature change)?**

Remove the unnecessary calls.

**Does this PR introduce a breaking change?**

No.

### CODE REVIEW

**Comment by kentcb** [comment]
@reactiveui/reviewers-core any of you fine people want to 👀 this?

**Comment by mteper** [comment]
LGTM. I imagine this was probably discussed in Slack, but if I were to be picky, I would say the one thing this bug description is missing is a bit of history -- how did those calls come to be in the first place?

**Comment by kentcb** [comment]
@mteper it's hard to say for sure due to the mangled history, but I believe this was just a vestige of the code's evolution. That is, at one point I had written it to use subjects to back `CanExecute` and `IsExecuting`. Consequently, I did the right thing and called `AsObservable` on those subjects. When I improved the code to remove the subjects, I neglected to remove the `AsObservable` calls.

How do you feel about merging this, following the process set out by @ghuntley?

**Comment by mteper** [comment]
I've limited time and I'll need to set up a dev environment. If this can wait a week or two, I'll gladly figure out where the process is documented and follow it. If this sounds like I'll be the bottleneck, then I'll bow out.

**Pull request merged**
