### PR TITLE
feature: Xamarin.Mac (unified) now compiles on windows

### PR DESCRIPTION
**Pull request by ghuntley**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Feature

**What is the current behavior? (You can also link to an open issue here)**

Xamarin.Mac was not being compiled or distributed in the NuGet packages.

**What is the new behavior (if this is a feature change)?**

Xamarin.Mac was using a private targeting pack; now that Xamarin has released an official targeting pack that's supported end-to-end it's time to start using it and shipping support for the platform once again in our NuGet packages.

**Does this PR introduce a breaking change?**

No

**Please check if the PR fulfills these requirements**
- [x] The commit follows our guidelines: https://github.com/reactiveui/reactiveui#contribute
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by b-straub** [comment]
Xamarin Studio on OS X can't build the Mac target.
Reason, change inside ReactiveUI_Mac.csproj:

`
<Import Project="$(MSBuildExtensionsPath)\Xamarin\Mac\Xamarin.Mac.CSharp.targets" Condition=" '$(OS)' == 'Windows_NT' " />
`

should be

`
<Import Project="$(MSBuildExtensionsPath)\Xamarin\Mac\Xamarin.Mac.CSharp.targets" Condition=" '$(OS)' != 'Windows_NT' " />
`

**Comment by ghuntley** [comment]
Can you open a new issue please.

 `'$(OS)' == 'Windows_NT'` is correct. It's how we compile Mac on Windows. Whats needed most likely is the inverse osx line.

**Comment by b-straub** [comment]
I can check the issue and fix on both sides MAC/Windows but I have no clue yet how to build Xamarin.Mac and the events file on Windows.
I have VS2015 with Xamarin installed and can build iOS targets without problems, running the build script throws and error when trying to generate the events file for Mac.

Currently also the official 7.1 nuget doesn't install on a Xamarin.Mac project (stable channel).

If you let kindly let me know what I miss as build perquisites I will investigate how to fix.

**Comment by b-straub** [comment]
PR #1287 creates a unified version for the targets that will build on XS, VS, cmd

**Pull request merged**
