### PR TITLE
Reactive Xamarin.Forms pages implementations

### PR DESCRIPTION
**Pull request by michaelstonis**
Includes additional Xamarin.Forms pages setup for Reactive UI. 

Also, I bumped up the version of Xamarin.Forms referenced, but this can be excluded. There have been some API changes since 1.5, but nothing too major.

### CODE REVIEW

**Comment by ghuntley** [comment]
LGTM.

**Comment by kentcb** [comment]
Thanks @michaelstonis . Unfortunately, the XamForms events project file includes a path to the XF binary under the packages directory (which includes the version). Could you please update that reference to use the new version too? Otherwise, XF events won't build.

**Comment by kentcb** [comment]
This is the line I was talking about, but also looks like it's necessary to upgrade the XF packages for that project.

**Comment by michaelstonis** [comment]
Upgraded. Totally missed the events package. It had been broken for so long... Excited to have it back.

**Comment by kentcb** [comment]
Thanks @michaelstonis !

**Pull request merged**
