### PR TITLE
EventBuilder / Events for Winforms / ActivationForViewFetcher for Winforms

### PR DESCRIPTION
**Pull request by Asesjix**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**
Bug fix, feature

**What is the current behavior? (You can also link to an open issue here)**
#1565 , #1627, #1016, #758

**What is the new behavior (if this is a feature change)?**
- Check for design time
~~- Use for Form the activated and deactivate event~~
- Fix path to Windows.winmd in EventBuilder UWP
- Change path to reference assemblies in EventBuilder WPF (because .net 4.6.1 is delivered)
- Add 0108 warning disable in EventBuilder template
- Add event support for (all?) Winform controls
  - BackgroundWorker
  - EventLog
  - FileSystemWatcher
  - PerformanceCounter
  - Process
  - SerialPort
  - DataSet
  - DirectoryEntry
  - DirectorySearcher
  - PrintDocument
  - MessageQueue
  - BindingNavigator
  - ToolStripButton
  - ToolStripLabel
  - ToolStripButton
  - ToolStripButton
  - ToolStripButton
  - ToolStripSeparator
  - ToolStripTextBox
  - ToolStripSeparator
  - ToolStripButton
  - ToolStripButton
  - ToolStripSeparator
  - BindingSource
  - Button
  - CheckBox
  - CheckedListBox
  - ColorDialog
  - ComboBox
  - ContextMenuStrip
  - DataGridView
  - DateTimePicker
  - DomainUpDown
  - ErrorProvider
  - WebBrowser
  - VScrollBar
  - TreeView
  - ToolStripContainer
  - TrackBar
  - ToolStrip
  - SplitContainer
  - TabControl
  - TabPage
  - TableLayoutPanel
  - TextBox
  - TabPage
  - StatusStrip
  - Splitter
  - RichTextBox
  - RadioButton
  - PropertyGrid
  - ProgressBar
  - PrintPreviewControl
  - PictureBox
  - Panel
  - NumericUpDown
  - MonthCalendar
  - MaskedTextBox
  - ListView
  - ListBox
  - LinkLabel
  - Label
  - HScrollBar
  - GroupBox
  - FlowLayoutPanel
  - MenuStrip
  - FolderBrowserDialog
  - FontDialog
  - HelpProvider
  - ImageList
  - NotifyIcon
  - OpenFileDialog
  - PageSetupDialog
  - PrintDialog
  - PrintPreviewDialog
  - SaveFileDialog
  - Timer
  - ToolTip
  - Chart
  - ServiceController

**What might this PR break?**

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:

### CODE REVIEW

**Comment by vatsalyagoel** [comment]
Can you rebase your code on top of develop and move the project to ReactiveUI.Events.sln. Also alter the PR to merge into develop? I can then retire PR #1633

**Comment by Asesjix** [comment]
Yes, I can do it. But only in about 10 hours.

**Comment by ghuntley** [comment]
I've got this. Will review on the train home tonight. This needs to be merged before #1623

**Comment by ghuntley** [comment]
image

Hmm, one failing test it seems. If the test is a false positive, remove otherwise will need resolving before merging. Otherwise LGTM - can't wait to get this in.

**Comment by Asesjix** [comment]
Hm has something changed? For me, the tests yesterday spat out no error.
I can test that as soon as I'm home. But that is only in about 6-7 hours :(

**Comment by Asesjix** [comment]
I just looked in my break times... The test always failed on the first run, the second time it was successful (WTF !?).
I have now restored the old logic so you should can merge the PR.

VS:
vs

**Comment by ghuntley** [comment]
<3 thank-you

**Pull request merged**
