### PR TITLE
"official" visual studio/resharper code snippets

### PR DESCRIPTION
**Pull request by ghuntley**
This PR is to design, discuss and eventually merge in what will be the "official" VS/R# code snipet templates:
- These are @pdoh00's snippets with some modifications. The original ones are at  https://gist.github.com/pdoh00/7435255
- Matt (@moswald) has his own which can be found in this PR.
- Paweł (@pbanka) has contributed https://gist.github.com/pmbanka/b4f51b5d3b055a2cdc97 for resharper.

I use Fody when working with RxUI so if someone else could step up and standardize/take ownership of this that would be :+1:

### CODE REVIEW

**Comment by AuroraDysis** [comment]
in ruiiv4.snippet
<Title>ReactiveUI - IViewFor<T></Title> is not a valid name.
Use &lt; and &gt; will fix it

**Comment by pdoh00** [comment]
I don't use ReSharper. Can someone else review?

**Comment by jonstodle** [comment]
Is there any way I can help out here? I'm using snippets extensively in VS and XS/VS4Mac when developing with RxUI.
I don't use R#, though.

**Comment by ghuntley** [comment]
@jonstodle yeah there is and that would be neat. Share your snippets for VS4Mac and VS4 and PR them in and we will make your snippets the official ones. Maybe some changes; probably not many :)

**Comment by ghuntley** [comment]
Closing out this GitHub issue as it was superseded by #1444

**Pull request closed without merging**
