### PR TITLE
make CompositeDisposable protected

### LINKED ISSUE #2783: Blazor: Make CompositeDisposable accessible from derived components
**Is your feature request related to a problem? Please describe.**

I want to easily hook to base component composite disposable in derived ReactiveComponentBase

**Describe the solution you'd like**

Make CompositeDisposable protected (or public)
https://github.com/reactiveui/ReactiveUI/blob/5c2665d27049add007e67bbb665b80e978925bd3/src/ReactiveUI.Blazor/ReactiveComponentBase.cs#L29

**Describe alternatives you've considered**

overriding virtual Dispose and using private CompositeDisposable. This works well but is not as clean and requires boilerplate

**Describe suggestions on how to achieve the feature**

Make CompositeDisposable protected
https://github.com/reactiveui/ReactiveUI/blob/5c2665d27049add007e67bbb665b80e978925bd3/src/ReactiveUI.Blazor/ReactiveComponentBase.cs#L29

**Additional context**

### PR DESCRIPTION
**Pull request by TenBuck**
**What kind of change does this PR introduce?**

resolve #2783

**What is the current behavior?**

CompositeDisposable was private

**What is the new behavior?**

CompositeDisposable is now protected

**What might this PR break?**

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:
Very small changes

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/reactiveui/ReactiveUI?pullRequest=2784) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/reactiveui/ReactiveUI?pullRequest=2784) before we can accept your contribution.<br/><br/>:x: TenBuck [sign now](https://cla.dotnetfoundation.org/reactiveui/ReactiveUI?pullRequest=2784)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/reactiveui/ReactiveUI?pullRequest=2784) it.</sub>

**Comment by worldbeater** [comment]
Just out of curiosity, why would you like to hook into that `CompositeDisposable`? I mean, there is a common [WhenActivated](https://reactiveui.net/docs/handbook/when-activated/)-based approach to subscriptions lifetime management, e.g. in the ctor of your view model or component you write somewhat like this:
```cs
// The "disposable" is a CompositeDisposable used to track subscription lifetimes.
// For ReactiveUI.Blazor, this disposable will dispose on component disposal.
this.WhenActivated(disposable =>
{
    observable.Subscribe(...).DisposeWith(disposable);
});
```

**Comment by glennawatson** [comment]
I'm not sure if that would potentially work at the moment with Blazor, if it isn't that might be the correct thing to fix.

**Comment by TenBuck** [comment]
> Just out of curiosity, why would you like to hook into that `CompositeDisposable`? I mean, there is a common [WhenActivated](https://reactiveui.net/docs/handbook/when-activated/)-based approach to subscriptions lifetime management, e.g. in the ctor of your view model or component you write somewhat like this:
> 
> ```cs
> 
> // The "disposable" is a CompositeDisposable used to track subscription lifetimes.
> 
> // With ReactiveUI.Blazor installed, this disposable will dispose on component disposal.
> 
> // This operates the same on other platforms as well.
> 
> this.WhenActivated(disposable =>
> 
> {
> 
>     observable.Subscribe(...).DisposeWith(disposable);
> 
> });
> 
> ```

WhenActivated doesn't work when the subscription depends on a parameter/injected service as it's still null when Activated is triggered. 

Not sure if this is intended behaviour as I am still fairly new to the framework

**Comment by glennawatson** [comment]
There's a interface called `ICanActivate` that we can derive from and call the `Activate` on the constructor, and `Deactivate` early in the Dispose method.

**Comment by TenBuck** [comment]
> There's a interface called `ICanActivate` that we can derive from and call the `Activate` on the constructor, and `Deactivate` early in the Dispose method.

I believe `Activate`should be called  either later in the lifecycle of a Blazor components as we'd still have the same problem with uninitialized parameters.

Perhaps in `OnInitialized` or `OnParametersSet` when firstRender is true?

I'll look into it after I catch some sleep

**Comment by glennawatson** [comment]
Sounds good, thanks for the assistance.

**Comment by exrezzo** [comment]
Hi, any news on this front? I'm trying to use the `WhenActivated` pattern, but the ReactiveComponentBase is not able to notify the backing VM. My actual workaround is simply calling 
```
protected override void OnAfterRender(bool firstRender)
    {
        base.OnAfterRender(firstRender);
        if (!firstRender) return;
        FollowUpViewModel.Activator.Activate();
    }

```

and
```
protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        FollowUpViewModel.Activator.Deactivate();
    }
```

Is there something that I can do to contribute? Sorry I'm a newbie, I've never collaborated to an open project and I would really like to do it, I'm loving this ReactiveUI project.

**Pull request closed without merging**
