### PR TITLE
Update the ReactiveUI.Wpf project to new format

### PR DESCRIPTION
**Pull request by bradphelan**
**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Attempts to update the ReactiveUI.WPF project to SDK format

### CODE REVIEW

**Comment by bradphelan** [comment]
The Cake file needs to pull in the submodule.

> "C:\projects\reactiveui\src\WpfNetStandardSample\CustomProjectSystem\CustomProject.props" was not found

Any idea how to do that?

**Comment by bradphelan** [comment]
I updated the YML file and it now seems to be working 
image

**Comment by bradphelan** [comment]
There is an error with the Nuget Pack of the WPF project

> C:\Program Files\dotnet\sdk\2.0.2\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(245,15): error MSB4064: The "AllowedOutputExtensionsInPackageBuildOutputFolder" parameter is not supported by the "PackTask" task. Verify the parameter exist

**Comment by bradphelan** [comment]
I'll wait till I get an answer on

https://stackoverflow.com/questions/47218910/what-is-the-source-of-the-error-allowedoutputextensionsinpackagebuildoutputfolde

**Comment by njannink** [comment]
I would just copy the files in your local repo instead of working with a submodule. If the remote repo breaks now also your build will break.

**Comment by bradphelan** [comment]
Hi @njannink this is just a temp work around for a feature that I hope within 6 month MS implements. WPF support in SDK style projects must be a short term goal for them ( I hope ). I don't think the upstream repo for the submodule is going anywhere and if the author fixes problems with it then integration is easier than copying files over.

**Comment by bradphelan** [comment]
@kentcb Was this helpful?

**Comment by kentcb** [comment]
@bradphelan totally - thanks!

I'm not sure that we're gonna merge it though, since it is likely to make a complicated build all the more complicated for little benefit. I suspect the right thing to do is wait for official support.

**Comment by bradphelan** [comment]
np

**Comment by onovotny** [comment]
Closing as this has been done.

**Pull request closed without merging**
