### PR TITLE
housekeeping: fixed broken link to stackoverflow

### PR DESCRIPTION
**Pull request by DamienDoumer**
I added stackoverflow link to the reactiveui tagged questions.

### CODE REVIEW

**Comment by ghuntley** [comment]
Thank-you @DamienDoumer for fixing this. Small yet super important improvement.

**Comment by DamienDoumer** [comment]
cool.

**Comment by ghuntley** [comment]
Congrats on your first PR btw!

**Comment by DamienDoumer** [comment]
thanks 👍

**Pull request merged**
